### ISSUE TITLE
Could you share the MSMT17-SCT file list?

### ISSUE THREAD

**Issue by ZelongZeng** [g3956/CCFP#1]
Hi, thank you very much for your sharing. I notice that you conducted experiments on three datasets including MSMT17-SCT, could you share the MSMT17-SCT file list?

**Comment by g3956** [comment]
Hi, the MSMT17-SCT file list has been uploaded.

**Comment by ZelongZeng** [comment]
OK, thank you very much! I will close this issue.

**Comment by YangJae96** [comment]
@ZelongZeng  

Hi, how did you generate MSMT17-SCT training set?

Did you use the MSMT17_v2?

**Comment by ZelongZeng** [comment]
> @ZelongZeng
> 
> Hi, how did you generate MSMT17-SCT training set?
> 
> Did you use the MSMT17_v2?

@YangJae96 
Hi, yes, I used MSMT17 and MSMT17-SCT file list to generate the training set.
