### ISSUE TITLE
About the cross-camera identity overlap ratio 

### ISSUE THREAD

**Issue by bryanduran99** [g3956/CCFP#5]
Thanks for your great work, and I have a question. what is the definition of cross-camera identity overlap ratio?

**Comment by g3956** [comment]
That means there are some identities that are captured on several cameras. This is possible in the real world.
But we do not know cross-camera supervision. We still regard them as different identities during training to validate the robustness of our method.

**Comment by bryanduran99** [comment]
“there are some identities that are captured on several cameras” ， several cameras means all the cameras or the cameras which the identities appear in the original datasets?
And how to select the some identities that are captured on several cameras. Random or there are some rules？
Thanks for your reply!

**Comment by g3956** [comment]
We randomly select a certain proportion of identities and add all the images from different cameras in the original dataset that share the same identity into the training set.

**Comment by bryanduran99** [comment]
OK, thanks!
